# Generated by Django 2.2.5 on 2021-02-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False),
        ),
    ]
