# Generated by Django 2.2.5 on 2021-02-16 12:36

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210216_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=0, validators=[question.models.under100]),
        ),
    ]
