# Generated by Django 2.2.5 on 2021-02-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.CharField(db_column='EXAMID', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='EXNAME', max_length=100)),
                ('start_time', models.DateTimeField(db_column='START')),
                ('end_time', models.DateTimeField(db_column='END')),
                ('organizer', models.ForeignKey(db_column='ORGANIZER', default=None, on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'EXAM',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('result', models.IntegerField(db_column='RESULT', default=0)),
                ('exam_id', models.ForeignKey(db_column='EXAMID', on_delete=django.db.models.deletion.CASCADE, to='exam.Exam')),
                ('user_id', models.ForeignKey(db_column='STUDENT', on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'ASSIGNMENT',
                'unique_together': {('user_id', 'exam_id')},
            },
        ),
    ]
