# Generated by Django 2.2.5 on 2021-02-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False),
        ),
    ]
