# Generated by Django 2.2.5 on 2021-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_assignment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='id',
            field=models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(db_column='EXAMID', max_length=20, primary_key=True, serialize=False),
        ),
    ]
