# Generated by Django 2.2.5 on 2021-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False)),
                ('saltkey', models.BinaryField(db_column='SALTKEY', default=b'')),
                ('password', models.BinaryField(db_column='PASSWORD', default=b'')),
                ('name', models.CharField(db_column='NAME', default='', max_length=30)),
                ('surname', models.CharField(db_column='SURNAME', default='', max_length=50)),
                ('mail', models.EmailField(db_column='EMAIL', max_length=254)),
                ('is_organizer', models.BooleanField(db_column='ISORGANIZER', default=False)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
    ]
