# Generated by Django 2.2.5 on 2021-02-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='id',
            field=models.CharField(auto_created=True, db_column='id', max_length=20, primary_key=True, serialize=False),
        ),
    ]
