# Generated by Django 2.2.5 on 2021-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210208_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='date_joined',
            field=models.DateTimeField(db_column='date_joined'),
        ),
    ]
