# Generated by Django 2.2.5 on 2021-02-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210208_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='date_joined',
            field=models.DateTimeField(auto_now=True, db_column='date_joined'),
        ),
    ]
