# Generated by Django 2.2.5 on 2021-02-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210208_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='id',
            field=models.CharField(db_column='id', max_length=20, primary_key=True, serialize=False),
        ),
    ]
